name: jarvis_ai
description: Продвинутый ИИ-ассистент Джарвис на Flutter через стабильный WebView.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2   # Самый стабильный официальный движок от Google

flutter:
  uses-material-design: true
